version: '3.1'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  app:
    container_name: sql-injection-sequelize-2
    build: .
    ports:
      - '8000:3000'
    depends_on:
      - mariadb
    links:
      - mariadb